### ISSUE TITLE
Git Check whether Branch exists.vi: Should check for greater or equal 0

### ISSUE THREAD

**Issue by pma-jup** [LV-APT/SimpleGit-Provider#9]
This VI should compare the search 1d array to greater or equal 0 as the output should be true if the branch exists. Otherwise (at least) the LeaveDailyBranch.vi is not working correctly as it tries to switch to a non-existing branch.

**Comment by nevstop** [comment]
@pma-jup, thank you for bringing this up. If you have a LabVIEW 2017 environment, please feel free to start a PR. Otherwise, I will fix it sooner or later.
